# Generated by Django 5.1.3 on 2024-11-26 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Portfolio_app", "0008_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="education",
            name="specialization",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="published",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies_used",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="certification",
            name="url",
            field=models.URLField(blank=True, default="http://example.com", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, default="http://example.com", null=True),
        ),
    ]
